version: '3.8'

services:
  test-runner:
    build:
      context: ./api
    command: ["python", "-m", "unittest", "discover"]
    volumes:
      - ./config:/config
    environment:
      - CONFIG_PATH=/config
